
//----------------------------------------------------
// The following code was generated by Java(tm) CUP v0.9d
// Sun Jan 07 17:10:10 EST 1996
//----------------------------------------------------

/** JavaCup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SEMI = 2;
  static final int EOF = 0;
  static final int DIVIDE = 6;
  static final int NUMBER = 10;
  static final int error = 1;
  static final int MINUS = 4;
  static final int TIMES = 5;
  static final int LPAREN = 8;
  static final int RPAREN = 9;
  static final int MOD = 7;
  static final int PLUS = 3;
};

